<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>nwod</string>
	</array>
	<key>name</key>
	<string>NWoD Character Sheet</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.nwod</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Tags like @appearance and @group</string>
			<key>match</key>
			<string>^@(\w+)</string>
			<key>name</key>
			<string>keyword.other.nwod</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^--(Stats)--$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.nwod</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Special --Stats-- section</string>
			<key>end</key>
			<string>(?=^--)</string>
			<key>name</key>
			<string>meta.section.stats.nwod</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(?i)(derived|advantages)$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.nwod</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Derived attributes subsection</string>
					<key>end</key>
					<string>^(?!(\s+|\s*$))</string>
					<key>name</key>
					<string>meta.subsection.derived.nwod</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?i)\s+(armor)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.other.armor.nwod</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Armor stat</string>
							<key>end</key>
							<string>$</string>
							<key>name</key>
							<string>meta.variable.derived.armor.nwod</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>constant.numeric.armor.nwod</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>keyword.operator.nwod</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>constant.numeric.armor.nwod</string>
										</dict>
										<key>4</key>
										<dict>
											<key>name</key>
											<string>support.constant.bulletproof.nwod</string>
										</dict>
									</dict>
									<key>comment</key>
									<string>Armor rating</string>
									<key>match</key>
									<string>(\d+)(?:(/)(\d+)(b)?)?</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#parenComment</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?i)\s+(virtue)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.other.virtue.nwod</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Virtue stat</string>
							<key>end</key>
							<string>$</string>
							<key>name</key>
							<string>meta.variable.derived.virtue.nwod</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#virtues</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?i)\s+(vice)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.other.vice.nwod</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Vice stat</string>
							<key>end</key>
							<string>$</string>
							<key>name</key>
							<string>meta.variable.derived.vice.nwod</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#vices</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?i)\s+(seeming)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.other.seeming.nwod</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Seeming stat</string>
							<key>end</key>
							<string>$</string>
							<key>name</key>
							<string>meta.variable.derived.seeming.nwod</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#seemings</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#parenComment</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?i)\s+(kith)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.other.kith.nwod</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Kith stat</string>
							<key>end</key>
							<string>$</string>
							<key>name</key>
							<string>meta.variable.derived.kith.nwod</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#kiths</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#parenComment</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\s+(\w+(?: \w+)*)\s+(?:([•|\d]+)|(\w+))</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.other.nwod</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.nwod</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>constant.character.nwod</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Generic derived stat</string>
							<key>end</key>
							<string>$</string>
							<key>name</key>
							<string>meta.variable.derived.nwod</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#parenComment</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(?i)(weapons?|attacks?)$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.nwod</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Attacks/weapons subsection</string>
					<key>end</key>
					<string>^(?!(\s+|\s*$))</string>
					<key>name</key>
					<string>meta.subsection.attacks.nwod</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#weapons</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(?i)(merits)$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.nwod</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Merits subsection</string>
					<key>end</key>
					<string>^(?!(\s+|\s*$))</string>
					<key>name</key>
					<string>meta.subsection.merits.nwod</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>^(\s+)(\w+(?: [\w\d\(\)\-\+]+)*)\s+([•|\d]+)</string>
							<key>beginCaptures</key>
							<dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.other.nwod</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.nwod</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Merit blocks`</string>
							<key>end</key>
							<string>^(?!(\1\s+|\s*$))</string>
							<key>name</key>
							<string>meta.merit.nwod</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(\w[\w ]+)$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.nwod</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Subsections like `attributes` and `skills`</string>
					<key>end</key>
					<string>^(?!(\s+|\s*$))</string>
					<key>name</key>
					<string>meta.subsection.nwod</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#skills</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.nwod</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Sections like --Notes-- and --Appearance--</string>
			<key>match</key>
			<string>^--(.+)--$</string>
			<key>name</key>
			<string>meta.section.nwod</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.markdown</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>kiths</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Kith keyword</string>
					<key>match</key>
					<string>(?ix) \b(
  Broadback | Hunterheart | Runnerswift | Skitterskulk |
  Steepscrambler | Swimmerskin | Venombite | Windwing |
  Antiquarian | Gravewight | Leechfinger | Mirrorskin | Tunnelgrub |
  Lurkglider |
  Airtouched | Earthbones | Fireheart | Manikin | Snowskin | Waterborn |
  Woodblood | Sandharrowed |
  Bright One | Dancer | Draconic | Flowering | Muse | Telluric |
  Treasured |
  Cyclopean | Farwalker | Gargantuan | Gristlegrinder | Stonebones |
  Waterdweller |
  Artist | Brewer | Cjate;aome | Chirurgeon | Oracle | Smith | Soldier |
  Woodwalker
)\b</string>
					<key>name</key>
					<string>support.constant.kith.nwod</string>
				</dict>
			</array>
		</dict>
		<key>parenComment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>comment</key>
					<string>Comments</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>comment.line.parenthesis.nwod</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parenComment</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>rangeValues</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.shortrange.nwod</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.medrange.nwod</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.longrange.nwod</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Range listings like 20/40/80</string>
					<key>match</key>
					<string>(\d+)/(\d+)/(\d+)</string>
					<key>name</key>
					<string>meta.variable.rangevalues.nwod</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.numeric.shortrange.nwod</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant.numeric.medrange.nwod</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant.numeric.longrange.nwod</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Range placeholder s/m/l</string>
					<key>match</key>
					<string>(s)/(m)/(l)</string>
					<key>name</key>
					<string>meta.constant.rangevalues.nwod</string>
				</dict>
			</array>
		</dict>
		<key>rollmod</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>comment</key>
					<string>Roll modifiers like `[8-again]`</string>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>meta.roll.parameters.nwod</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.function.language.nwod</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.function.nwod</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.parameters.nwod</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>General modifiers</string>
							<key>match</key>
							<string>\b(?:((?:10-again|9-again|8-again|rote)\??)|([\w\d+_\-\/]*))\s*(?:([,\s])|(?=[\n\]]))</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>seemings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Seeming keyword</string>
					<key>match</key>
					<string>(?ix) \b(
  Beast | Darkling | Elemental | Fairest | Ogre | Wizened
)\b</string>
					<key>name</key>
					<string>support.constant.seeming.nwod</string>
				</dict>
			</array>
		</dict>
		<key>sizeValues</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.size.nwod</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.nwod</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant.character.concealment.nwod</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Size listings like 1/S and 2/J</string>
					<key>match</key>
					<string>(\d+)(?:(/)([psjlnPSJLN]))?</string>
					<key>name</key>
					<string>meta.variable.size.nwod</string>
				</dict>
			</array>
		</dict>
		<key>skills</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s+(\w+(?: [\w\(\)\d]+)*)\s+([•|\d]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other.nwod</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.nwod</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Skills, attributes, power names, etc.</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.variable.nwod</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.arithmetic.nwod</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.nwod</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Magical bonuses like `+ 2` and `+3`</string>
							<key>match</key>
							<string>(\+)\s*(\d+)</string>
							<key>name</key>
							<string>meta.variable.nwod</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\()</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.parameters.begin.nwod</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Skill specialties like `(crime scenes)`</string>
							<key>end</key>
							<string>(\))</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.parameters.begin.nwod</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.skill.specialty.nwod</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.nwod</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>punctuation.separator.sequence.nwod</string>
										</dict>
									</dict>
									<key>comment</key>
									<string>Individual skill specialties are a comma-separated list</string>
									<key>match</key>
									<string>([\s\w]+)(,)?</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#rollmod</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>vices</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Vice keyword</string>
					<key>match</key>
					<string>(?ix) \b(
  Envy | Gluttony | Greed | Lust | Pride | Sloth | Wrath
)\b</string>
					<key>name</key>
					<string>support.constant.vice.nwod</string>
				</dict>
			</array>
		</dict>
		<key>virtues</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Virtue keyword</string>
					<key>match</key>
					<string>(?ix) \b(
  Charity | Faith | Fortitude | Hope | Justice | Prudence | Temperance
)\b</string>
					<key>name</key>
					<string>support.constant.virtue.nwod</string>
				</dict>
			</array>
		</dict>
		<key>weapons</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(\s+)[\w.]+</string>
					<key>comment</key>
					<string>Items like `pistol - stats - pools`</string>
					<key>end</key>
					<string>^(?!(\1\s+|\s*$))</string>
					<key>name</key>
					<string>meta.weapon.nwod</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>^\s+</string>
							<key>comment</key>
							<string>Attachments, mods, and notes</string>
							<key>end</key>
							<string>$</string>
							<key>name</key>
							<string>meta.weapon.notes.nwod</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(range)\s</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.nwod</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Range designator</string>
							<key>end</key>
							<string>(?=,|\s*\-)</string>
							<key>name</key>
							<string>meta.stats.range.nwod</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#rangeValues</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.nwod</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.mag.nwod</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.nwod</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.mag.chambered.nwod</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Magazine capacity</string>
							<key>match</key>
							<string>(mag)\s+(\d+)(?:(\+)(\d))?</string>
							<key>name</key>
							<string>meta.stats.mag.nwod</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(size)\s</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.nwod</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Item size</string>
							<key>end</key>
							<string>(?=,|\s*\-)</string>
							<key>name</key>
							<string>meta.stats.size.nwod</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#sizeValues</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#parenComment</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(atk)(?:\s+(\d+))?</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.nwod</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.atk.nwod</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Summed attack pool</string>
							<key>end</key>
							<string>(?=\-|\s*$)</string>
							<key>name</key>
							<string>meta.stats.atk.nwod</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#rollmod</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#rangeValues</string>
								</dict>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.other.attribute-name.nwod</string>
										</dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>keyword.operator.nwod</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>constant.numeric.aim.nwod</string>
										</dict>
									</dict>
									<key>comment</key>
									<string>First round aim bonus</string>
									<key>match</key>
									<string>(aim)\s+(\+)(\d+)</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.nwod</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.nwod</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>support.constant.character.damagetype.nwod</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Damage code like 3B or 4L</string>
							<key>match</key>
							<string>\s(?:(dam(?:age)?)\s+)?(\d+)([lbaLBA])?</string>
							<key>name</key>
							<string>meta.damage.nwod</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#rollmod</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.plain.nwod</string>
	<key>uuid</key>
	<string>7aa94fe0-ea77-4175-a58b-d903dbe28309</string>
</dict>
</plist>
