# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'npc/gui/uis/new_character.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewCharacterDialog(object):
    def setupUi(self, NewCharacterDialog):
        NewCharacterDialog.setObjectName("NewCharacterDialog")
        NewCharacterDialog.resize(441, 352)
        NewCharacterDialog.setModal(True)
        self.verticalLayoutWidget = QtWidgets.QWidget(NewCharacterDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 441, 349))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.infoForm = QtWidgets.QFormLayout()
        self.infoForm.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.infoForm.setObjectName("infoForm")
        self.typeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.typeLabel.setObjectName("typeLabel")
        self.infoForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.typeLabel)
        self.typeSelect = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.typeSelect.setObjectName("typeSelect")
        self.infoForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.typeSelect)
        self.nameLine = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nameLine.setObjectName("nameLine")
        self.infoForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nameLine)
        self.characterName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.characterName.setObjectName("characterName")
        self.infoForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.characterName)
        self.groupLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.groupLabel.setObjectName("groupLabel")
        self.infoForm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.groupLabel)
        self.groupName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.groupName.setObjectName("groupName")
        self.infoForm.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.groupName)
        self.verticalLayout.addLayout(self.infoForm)
        self.foreignBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foreignBox.sizePolicy().hasHeightForWidth())
        self.foreignBox.setSizePolicy(sizePolicy)
        self.foreignBox.setMinimumSize(QtCore.QSize(0, 71))
        self.foreignBox.setCheckable(True)
        self.foreignBox.setChecked(False)
        self.foreignBox.setObjectName("foreignBox")
        self.foreignText = QtWidgets.QLineEdit(self.foreignBox)
        self.foreignText.setGeometry(QtCore.QRect(10, 30, 301, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foreignText.sizePolicy().hasHeightForWidth())
        self.foreignText.setSizePolicy(sizePolicy)
        self.foreignText.setClearButtonEnabled(True)
        self.foreignText.setObjectName("foreignText")
        self.verticalLayout.addWidget(self.foreignBox)
        self.deceasedBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deceasedBox.sizePolicy().hasHeightForWidth())
        self.deceasedBox.setSizePolicy(sizePolicy)
        self.deceasedBox.setMinimumSize(QtCore.QSize(0, 101))
        self.deceasedBox.setCheckable(True)
        self.deceasedBox.setChecked(False)
        self.deceasedBox.setObjectName("deceasedBox")
        self.deceasedText = QtWidgets.QPlainTextEdit(self.deceasedBox)
        self.deceasedText.setGeometry(QtCore.QRect(10, 30, 301, 61))
        self.deceasedText.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.deceasedText.setObjectName("deceasedText")
        self.verticalLayout.addWidget(self.deceasedBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.typeLabel.setBuddy(self.typeSelect)
        self.nameLine.setBuddy(self.characterName)
        self.groupLabel.setBuddy(self.groupName)

        self.retranslateUi(NewCharacterDialog)
        QtCore.QMetaObject.connectSlotsByName(NewCharacterDialog)
        NewCharacterDialog.setTabOrder(self.typeSelect, self.characterName)
        NewCharacterDialog.setTabOrder(self.characterName, self.groupName)
        NewCharacterDialog.setTabOrder(self.groupName, self.foreignBox)
        NewCharacterDialog.setTabOrder(self.foreignBox, self.foreignText)
        NewCharacterDialog.setTabOrder(self.foreignText, self.deceasedBox)
        NewCharacterDialog.setTabOrder(self.deceasedBox, self.deceasedText)

    def retranslateUi(self, NewCharacterDialog):
        _translate = QtCore.QCoreApplication.translate
        NewCharacterDialog.setWindowTitle(_translate("NewCharacterDialog", "New Character"))
        self.typeLabel.setText(_translate("NewCharacterDialog", "T&ype"))
        self.nameLine.setText(_translate("NewCharacterDialog", "&Name"))
        self.groupLabel.setText(_translate("NewCharacterDialog", "&Group"))
        self.foreignBox.setTitle(_translate("NewCharacterDialog", "Foreig&n"))
        self.foreignText.setPlaceholderText(_translate("NewCharacterDialog", "Where do they live?"))
        self.deceasedBox.setTitle(_translate("NewCharacterDialog", "&Deceased"))
        self.deceasedText.setPlaceholderText(_translate("NewCharacterDialog", "How did they die?"))

