npc:
  version: 2.0.0
  tags:
    type:
      desc: The character type of an npc
      required: true
      max: 1
    faketype:
      desc: A false character type that will be shown in listings. Useful for hiding that the town priest is secretly a vampire.
      max: 1
    name:
      desc: An additional name the character uses.
    realname:
      desc: The true primary name for the character. Useful when the real name uses characters that are not allowed in a filename.
      max: 1
    title:
      desc: Honorific title for the character, like The Kingslayer.
    pronouns:
      desc: Pronouns the character uses. Particularly useful for androgynous fantasy races.
    gender:
      desc: Gender role this character has.
    appearance:
      desc: What the character looks like to other people.
    race:
      desc: Observable ancestry of the character. Extremely setting-dependent; anything from Greek and Egyptian, to Human and Elvish.
    age:
      desc: How old the character is.
    portrait:
      desc: Name of an image file to use for the character.
    location:
      desc: Broad description of where the character lives.
    region:
      desc: More specific area in which the character lives. Typically contained within their location.
    locale:
      desc: Even more specific area in which the character lives. Typically contained within their region.
    wanderer:
      desc: Signifies that the character has no permanent home. Optionally contains a description of their travel habits, etc.
      allow_empty: true
    foreign:
      desc: Signifies that the character does not live in the game's primary play area. Optionally contains a description of where they do live.
      allow_empty: true
    group:
      desc: Name of a group that the character belongs to.
      subtags:
        rank:
          desc: The character's rank or role within this group.
    employer:
      desc: Name of a person or organization that pays the character for work.
      subtags:
        job:
          desc: Name of the character's job at their employer.
    dead:
      desc: Signifies that the character is deceased. Optionally also contains a description of how they perished.
      allow_empty: true
    sticky:
      desc: Prevent this file from being moved by the reorg command
      no_value: true
      max: 1
    nolint:
      desc: Do not show linting errors for this character.
      no_value: true
      max: 1
    delist:
      desc: Do not show this character in listings.
      no_value: true
      max: 1
    hide:
      desc: Conceal the named tag from listings.
      doc: >
        Individual tag values can be hidden using [tagname] >> [value]. Hide all subtags using
        [parent] >> [value] >> subtags, or hide single subtag with [parent] >> [value] >> [subtag value]
  deprecated_tags:
    skip:
      desc: Do not show this character in listings.
      replaced_by: delist
      deprecated: 2.0.0
    keep:
      desc: Prevent this file from being moved by the reorg command
      replaced_by: sticky
      deprecated: 2.0.0
    hidegroup:
      desc: Hide a single named group.
      replaced_by: hide
      replace_pattern: "group >> $value"
      deprecated: 1.4.1
    hideranks:
      desc: Hide all ranks for a named group.
      replaced_by: hide
      replace_pattern: "group >> $value >> rank"
      deprecated: 1.4.1
  reserved_tags:
    description:
      desc: >
        Public text about this character, like who they are, their history, what they want, etc. This is an
        internal tag used to store bare text that appears in the tags area of npc sheets. It should not be
        used explicitly.
    mnemonic:
      desc: >
        One or two words that will jog your memory about this character. The mnemonic is supposed to help you
        easily browse character files, so it is part of the filename.
  tag_blocks:
    flags:
      - sticky
      - nolint
      - delist
    bio:
      - type
      - faketype
      - realname
      - name
      - title
      - pronouns
      - gender
      - race
      - age
      - portrait
      - appearance
      - dead
    geo:
      - location
      - region
      - locale
      - wanderer
      - foreign
    assoc:
      - group
      - employer
    rest:
      - "*"
campaign:
  create_on_init: []
  characters:
    path: Characters
    ignore_subpaths: []
    subpath_components:
      - selector: first_value
        tags: [type]
      - selector: first_value
        tags: [court]
      - selector: first_value
        tags: [freehold]
      - selector: first_value
        tags: [motley]
      - selector: first_value
        tags: [entitlement, group]
    listing:
      format: markdown
      sorting:
        - last
      base_header_level: 1
      metadata:
        title: NPC Listing
        timestamp: '%a, %b %d %I:%M%p'
    use_blocks:
      - flags
      - bio
      - geo
      - assoc
      - rest
  plot:
    path: Plot
    latest_index: 0
    filename_pattern: Plot ((NN)).md
    file_contents: ((COPY))
  session:
    path: Session History
    latest_index: 0
    filename_pattern: Session ((NN)).md
    file_contents: |
      Played:

      # (in-game date and time)
