npc:
  editor: ""
  report:
    format: markdown
  listing:
    format: markdown
    sorting:
      - last
    base_header_level: 1
    metadata:
      title: NPC Listing
      timestamp: '%a, %b %d %I:%M%p'
  reorg:
    path: "{type}/{type-social}/{type-political}/{type-squad}/{groups}"
  tags:
    - name: type
      desc: The character type of an npc
      required: true
      max: 1
    - name: faketype
      desc: A false character type that will be shown in listings. Useful for hiding that the town priest is secretly a vampire.
      max: 1
    - name: name
      desc: An additional name the character uses.
    - name: realname
      desc: The true primary name for the character. Useful when the real name uses characters that are not allowed in a filename.
      max: 1
    - name: location
      desc: Broad description of where the character lives.
    - name: region
      desc: More specific area in which the character lives. Typically contained within their location.
    - name: locale
      desc: Even more specific area in which the character lives. Typically contained within their region.
    - name: appearance
      desc: What the character looks like to other people.
    - name: race
      desc: Observable ancestry of the character. Extremely setting-dependent; anything from Greek and Egyptian, to Human and Elvish.
    - name: age
      desc: How old the character is.
    - name: portrait
      desc: Name of an image file to use for the character.
    - name: group
      desc: Name of a group that the character belongs to.
      subtags:
        - name: rank
          desc: The character's rank or role within this group.
    - name: employer
      desc: Name of a person or organization that pays the character for work.
      subtags:
        - name: job
          desc: Name of the character's job at their employer.
    - name: dead
      desc: Signifies that the character is deceased. Optionally also contains a description of how they perished.
      allow_empty: true
    - name: sticky
      desc: Prevent this file from being moved by the reorg command
      no_value: true
    - name: nolint
      desc: Do not show linting errors for this character.
      no_value: true
    - name: skip
      desc: Do not show this character in listings.
      no_value: true
    - name: wanderer
      desc: Signifies that the character has no permanent home. Optionally contains a description of their travel habits, etc.
      allow_empty: true
    - name: foreign
      desc: Signifies that the character does not live in the game's primary play area. Optionally contains a description of where they do live.
      allow_empty: true
deprecated_tags:
    - name: keep
      desc: Prevent this file from being moved by the reorg command
      replacement: sticky
