# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Binaries build and release

on:
  release:
    types: ["published"]
  push:
    branches: [ "build-process" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: pip
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build binary
      run: pyinstaller pyi/npc.spec
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: npc-${{ matrix.os }}
        path: release/*.zip
        retention-days: 1
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
      - name: Display artifacts
        run: ls -R
